### ISSUE TITLE
How to use your code to stitch?

### ISSUE THREAD

**Issue by zhongqiu1245** [minshu-kim/Recurrent-Elastic-Warp#3]
Hello, thank you for your amazing job!
Could you release a short/clear/usage code to stitch images with you work?
For example, what is the code like when I input 2 images? or 4, 5, ....images?
Thank you in advance!

**Comment by minshu-kim** [comment]
You can save the stitched images of [this variable](https://github.com/minshu-kim/Recurrent-Elastic-Warp/blob/5c5a5d33b588c8405fa6b1f3cbf676a4b043dc29/eval.py#L159).

This repository currently does not support Multiple image stitching.
