### ISSUE TITLE
Evaluation Problem

### ISSUE THREAD

**Issue by Greatxcw** [minshu-kim/Recurrent-Elastic-Warp#5]
Thank you very much for your wonderful work, I encountered the following problems when reproducing the code, please help me take a look.
![image](https://github.com/minshu-kim/Recurrent-Elastic-Warp/assets/118790158/7d31c8c3-1f76-40b9-95db-936ae1b36d74)

**Comment by minshu-kim** [comment]
Thanks for your interesting in our work.
Was there any generation of NaN PSNR in the validation stage on training?

+ Note that the error may be generated when the aligned images has no overlapping regions (or severe misalignment).

**Comment by minshu-kim** [comment]
Thanks for your interesting in our work.
Was there any generation of NaN PSNR in the validation stage on training?

\+ Note that the error may be generated when aligned images has no overlapping region due to failed estimation of elastic warps.

**Comment by Greatxcw** [comment]
Thank you for your reply ! There is no generation of NaN PSNR in the validation phase of training, but I'm using the weights you provided.

**Comment by Greatxcw** [comment]
Here's my training log.
[Uploading train_with_hcell_ckpt.txt…]()

**Comment by Greatxcw** [comment]
Here's my training log.
[train_with_hcell_ckpt.txt](https://github.com/user-attachments/files/15860814/train_with_hcell_ckpt.txt)

**Comment by Greatxcw** [comment]
I've solved the problem, it's the torch version, thank you again for your time.

**Comment by minshu-kim** [comment]
Thank you for sharing the solution.
Good luck with your study :)
