### ISSUE TITLE
How to generate stitched images?

### ISSUE THREAD

**Issue by liyi-la** [minshu-kim/Recurrent-Elastic-Warp#7]
Excellent work！Could you please  tell how to generate stitched images?eval.py can only calculate the metrics.

**Comment by minshu-kim** [comment]
Hi there,

Thanks for your interest in our work. This [variable](https://github.com/minshu-kim/Residual-Elastic-Warp/blob/c2addbd5189e040a124e4363a36a36dba0e7e177/eval.py#L172) represents a stitched image.
You can save this to generate the stitched images.

**Comment by liyi-la** [comment]
> Hi there,
> 
> Thanks for your interest in our work. This [variable](https://github.com/minshu-kim/Residual-Elastic-Warp/blob/c2addbd5189e040a124e4363a36a36dba0e7e177/eval.py#L172) represents a stitched image. You can save this to generate the stitched images.

Thanks！
